### PR TITLE
Integration tests fixes

### LINKED ISSUE #37: Update example filter
The example filter is outdated, and does not use the paths in the header correctly.  This needs to be fixed.

### PR DESCRIPTION
**Pull request by jessberg**
A range of various fixes I found while trying to do integration tests, and trying to make a new example filter.  They include
1. Running bookinfo for 7 ticks instead of 6, so that it has time to send things to storage.
2. Updating the example filter to a working version.  Note that it only sends to storage when reviews is reviews-v1, because it matches on that for isomorphism.  You can get it to make that graph by setting the seed to 0.
3. I renamed the file graph_utils to just utils;  it's too confusing to have the library and one of the files within it have the same name.
4. I fixed an isomorphism bug where, when we're checking whether one node's property set was a subset of another's set, I had the arguments in the wrong order.  So it was checking whether A was a subset of B instead of whether B was a subset of A.  It took a while to figure out the problem, so I've added the tests that helped me find it.

### CODE REVIEW

File: libs/graph_utils/src/iso.rs [hunk 1]
```diff
@@ -536,20 +623,33 @@ mod tests {
...
-        let prod = get_node_with_id(&graph_g, "productpage-v1".to_string()).unwrap();
-        let det = get_node_with_id(&graph_g, "details-v1".to_string()).unwrap();
-        let rev = get_node_with_id(&graph_g, "reviews-v1".to_string()).unwrap();
+        let mut mapping = mapping_wrapped.unwrap();
+        let mut a = get_node_with_id(&graph_h, "a".to_string()).unwrap();
+        let mut b = get_node_with_id(&graph_h, "b".to_string()).unwrap();
+        let mut c = get_node_with_id(&graph_h, "c".to_string()).unwrap();
+        let mut prod = get_node_with_id(&graph_g, "productpage-v1".to_string()).unwrap();
+        let mut det = get_node_with_id(&graph_g, "details-v1".to_string()).unwrap();
+        let mut rev = get_node_with_id(&graph_g, "reviews-v1".to_string()).unwrap();
```
Comment (fruffy) [inline libs/graph_utils/src/iso.rs]: Why does all of this have to be mutable? I am assuming it is because you are overwriting this variable later?

File: example_envs/bookinfo/main.rs [hunk 2]
```diff
@@ -110,7 +110,7 @@ fn main() {
 
     // Execute the simulator
     simulator.insert_rpc("gateway", Rpc::new("0"));
-    for tick in 0..6 {
+    for tick in 0..7 {
```
Comment (fruffy) [inline example_envs/bookinfo/main.rs:113]: You should also add a test for this in the integration test suite we have. Main is not really used at all.

File: libs/filter_example/src/example_filter.rs [hunk 3]
```diff
@@ -52,213 +95,364 @@ impl Filter {
...
-            mod_rpc
-                .headers
-                .get_mut(&"properties".to_string())
-                .unwrap()
-                .push_str(&me);
-        } else {
-            mod_rpc.headers.insert("properties".to_string(), me);
+    pub fn store_headers(&mut self, x: Rpc) {
+        // store path as well as properties
+        let prop_str = format!("{uid}_properties_path", uid = x.uid);
```
Comment (fruffy) [inline libs/filter_example/src/example_filter.rs:133]: Is this the code that is meant to go into the envoy filter, too?

**Review by fruffy — CHANGES_REQUESTED** [review]

File: libs/graph_utils/src/iso.rs (hunk 1 above)
Comment (jessberg) [reply libs/graph_utils/src/iso.rs]: Yes, there's two testing conditions in that test.  First, we test whether bookinfo and a three node graph match when the three node graph is a parent with two children.  Then we test whether bookinfo and a three node graph match when the three node graph is a chain.

File: example_envs/bookinfo/main.rs (hunk 2 above)
Comment (jessberg) [reply example_envs/bookinfo/main.rs:113]: Yeah, I'm getting this fixed, then I'll get the compiler fixed, and then we'll have big integration tests.

File: libs/filter_example/src/example_filter.rs (hunk 3 above)
Comment (jessberg) [reply libs/filter_example/src/example_filter.rs:133]: Yes.  It stores the path and any other collected properties using the form uid_properties_property_name in the envoy shared data.

File: example_envs/bookinfo/main.rs (hunk 2 above)
Comment (fruffy) [reply example_envs/bookinfo/main.rs:113]: Oh I meant the tests in the tests folder. This is likely a 3 line change. Main should not be used for testing at all. It is just an example.

File: libs/graph_utils/src/iso.rs (hunk 1 above)
Comment (fruffy) [reply libs/graph_utils/src/iso.rs]: Why not create new variables for this? Also reduces the possibility of making mistakes.

Comment (jessberg) [reply libs/graph_utils/src/iso.rs]: That makes sense.  Should be distinct variables now.

File: example_envs/bookinfo/main.rs (hunk 2 above)
Comment (jessberg) [reply example_envs/bookinfo/main.rs:113]: Oh I see.  Yeah, that's a good idea.  Should be in there now.

File: example_envs/tests/bookinfo_test.rs [hunk 4]
```diff
@@ -5,13 +5,15 @@ use example_envs::productpage::ProductPage;
 use example_envs::reviews::Reviews;
 use queues::IsQueue;
 use rpc_lib::rpc::Rpc;
+use std::path::PathBuf;
 
 #[test]
 fn check_bookinfo() {
-    // Set up library access
+    // Set up plugin name
+    let plugin_str = "../target/debug/libfilter_example.dylib";
```
Comment (fruffy) [inline example_envs/tests/bookinfo_test.rs]: I am surprised this passes. Is there some change in the way filters are loaded? dylibs only exist on MacOS.

Comment (jessberg) [reply example_envs/tests/bookinfo_test.rs]: I just copy pasted from main - I fixed that now.  No, I didn't change anything from how filters are loaded;  the only thing I changed in the plugin file was adding routing info to RPCs to get the filter to accept them.

Comment (fruffy) [reply example_envs/tests/bookinfo_test.rs]: Yeah we have some code that sets the extension based on the OS, so that is why it works. Was just surprised.

**Review by fruffy — APPROVED** [review]
