### PR TITLE
Edge fixes

### LINKED ISSUE #36: Change to logging
We should stop printing out information that isn't the simulator's output and instead use logging.

### PR DESCRIPTION
**Pull request by fruffy**
This pull request readds edges back into the simulator. It also adds logging and facilities to test bookinfo properly. 

#### Edges
The way we handle edges is that we add an intermediate step into the tick of the simulator. Edges are not part of the elements map anymore, instead they are a separate entity that glues everything together. When we tick, we first gather all the RPCs from all the nodes, and then place them into an edge according to source and destination. If that edge does not exist, an assert fires. The edge then keeps this RPC as long as it has delay. We then gather all the RPCs from the edges and place them into the destination nodes.
#### Logging
I instrumented logging everywhere in the simulator. It should replace panics and prints as much as possible. The nice part is that it gives you colour-coded output so you can easily distinguish statements. It also saves a log file called `sim.log` with every run. Makes reading the simulator output a little easier. Also formatted output a little.
#### Bookinfo testing 
Gateways do not produce RPCs continuously now. Instead, we place an RPC directly in the node, which is propagated through. This makes it easier to observe behaviour across several stages. I added a per-step test for this. In addition, you can now get nodes from the simulator and inspect them. This allows us to test specific functionality. 

This turned into quite the extensive pull request. I can break this up if requested. 
Fixes #36

### CODE REVIEW

File: example_envs/bookinfo/gateway.rs [hunk 1]
```diff
@@ -20,22 +25,54 @@ impl fmt::Display for Gateway {
...
-            outbound_rpc
-                .headers
-                .insert("direction".to_string(), "request".to_string());
-            outbound_rpc
-                .headers
-                .insert("src".to_string(), self.core_node.id.to_string());
-            outbound_rpc
-                .headers
-                .insert("dest".to_string(), "productpage-v1".to_string());
+        log::error!("{:?}", self.core_node.generation_rate);
```
Comment (jessberg) [inline example_envs/bookinfo/gateway.rs]: Should we be logging this as an error?  It looks like it's just info.

File: example_envs/bookinfo/gateway.rs [hunk 2]
```diff
@@ -20,22 +25,54 @@ impl fmt::Display for Gateway {
...
-    fn recv(&mut self, _rpc: Rpc, _tick: u64) {
-        // we discard anything we receive
+    fn recv(&mut self, rpc: Rpc, tick: u64) {
+        if let Some(direction) = rpc.headers.get("direction") {
+            if direction == "response" {
+                self.collected_responses.push(rpc);
+            }
+        } else {
+            // RPC without direction information, just pass it on
+            self.core_node.recv(rpc, tick);
```
Comment (jessberg) [inline example_envs/bookinfo/gateway.rs:73]: Shouldn't we raise an error if an RPC has no direction information?

File: libs/sim/simulator.rs [hunk 3]
```diff
@@ -69,43 +94,45 @@ impl Simulator {
         self.add_node(id, node);
     }
 
-    pub fn add_edge(&mut self, delay: u32, element1: &str, element2: &str, unidirectional: bool) {
-        if !self.elements.contains_key(element1) {
+    pub fn insert_rpc(&mut self, target: &str, rpc: Rpc) {
```
Comment (jessberg) [inline libs/sim/simulator.rs:97]: What is the purpose of this function?

File: example_envs/bookinfo/gateway.rs (hunk 1 above)
Comment (fruffy) [reply example_envs/bookinfo/gateway.rs]: Yeah that should not be there at all.

File: example_envs/bookinfo/gateway.rs (hunk 2 above)
Comment (fruffy) [reply example_envs/bookinfo/gateway.rs:73]: I do not know, gateway is kind of dumb so it fills that information anyway. If it gets a directionless RPC that is being forwarded to productpage.

File: libs/sim/simulator.rs (hunk 3 above)
Comment (fruffy) [reply libs/sim/simulator.rs:97]: It is basically a manually RPC generation function. Instead of having nodes with generation rate, which creates too much noise, we place an RPC directly in the receive queue of a particular node. Makes it much easier to test. You can see an example of that in the bookinfo_tests.

File: example_envs/bookinfo/gateway.rs (hunk 2 above)
Comment (jessberg) [reply example_envs/bookinfo/gateway.rs:73]: Okay, I guess the tests will guarantee that never happens anyway.

File: libs/sim/simulator.rs (hunk 3 above)
Comment (jessberg) [reply libs/sim/simulator.rs:97]: Gotcha

**Review by jessberg — APPROVED** [review]
